from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from fastapi.staticfiles import StaticFiles
from fastapi.responses import FileResponse
import mysql.connector
import os
from dotenv import load_dotenv

load_dotenv()
app = FastAPI()

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"], # Allows all origins for development
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

def get_db_connection():
    return mysql.connector.connect(
        host=os.getenv('DB_HOST', 'localhost'),
        user=os.getenv('DB_USER', 'root'),
        password=os.getenv('DB_PASSWORD', ''),
        database=os.getenv('DB_NAME', 'cllege_results')
    )

@app.get("/api/results/{register_no}")
def get_results(register_no: str):
    conn = None
    try:
        conn = get_db_connection()
        cursor = conn.cursor(dictionary=True)
        
        query = "SELECT student_name, semester, subject_code, subject_name, grade, result_status as Result FROM results WHERE register_no = %s"
        cursor.execute(query, (register_no,))
        rows = cursor.fetchall()
        
        if not rows:
            raise HTTPException(status_code=404, detail="please entry the vaild register_no")
        
        # Extract student_name directly from the database response
        student_name = rows[0].get('student_name') if rows else "HARISANKAR S"
            
        return {
            "register_no": register_no,
            "student_name": student_name,
            "results": rows
        }
    except mysql.connector.Error as err:
        raise HTTPException(status_code=500, detail="Database connection error")
    finally:
        if conn and conn.is_connected():
            cursor.close()
            conn.close()

# Serve React App
frontend_dist = os.path.join(os.path.dirname(__file__), "..", "frontend", "dist")

# Mount the assets directory (contains CSS and JS generated by Vite)
if os.path.exists(os.path.join(frontend_dist, "assets")):
    app.mount("/assets", StaticFiles(directory=os.path.join(frontend_dist, "assets")), name="assets")

# Optional: Mount other static files if they exist (vite-svg, favicon etc can be handled here or as specific file responses)
# For simplicity, catch-all routing for any paths not starting with /api to serve index.html
@app.get("/{catchall:path}")
def serve_react_app(catchall: str):
    file_path = os.path.join(frontend_dist, catchall)
    if os.path.exists(file_path) and os.path.isfile(file_path):
        return FileResponse(file_path)
    return FileResponse(os.path.join(frontend_dist, "index.html"))
